spring:
  jpa:
    database: MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/springhealth_user
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver