customProperty: customProperty

redis.server: 127.0.0.1
redis.port: 6379

spring:
  jpa:
    database: MYSQL
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/springhealth_intervention
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver