spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:springhealthconfig,classpath:springhealthconfig/userservice,classpath:springhealthconfig/deviceservice,classpath:springhealthconfig/interventionservice
server:
  port: 8201
eureka:
  instance:
    preferIpAddress: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://eureka1:8001/eureka/,http://eureka2:8002/eureka/

# config